controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: effort_controllers/JointGroupEffortController

velocity_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4